a
No exception
b
Uncaught exception Backtrace3.Error("b")
Raised at file "backtrace3.ml", line 7, characters 16-32
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 11, characters 4-11
Re-raised at file "backtrace3.ml", line 20, characters 41-50
Called from file "backtrace3.ml", line 28, characters 11-23
Uncaught exception Backtrace3.Error("c")
Raised at file "backtrace3.ml", line 24, characters 6-23
Called from file "backtrace3.ml", line 28, characters 11-23
Uncaught exception Backtrace3.Error("d")
Raised at file "backtrace3.ml", line 7, characters 16-32
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 7, characters 42-53
Called from file "backtrace3.ml", line 11, characters 4-11
Called from file "backtrace3.ml", line 28, characters 11-23
Uncaught exception Invalid_argument("index out of bounds")
Raised by primitive operation at file "backtrace3.ml", line 28, characters 14-22
