Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Backtrace.foo in file "backtrace.ml", line 9, characters 11-27
Called from Backtrace.bar in file "backtrace.ml", line 17, characters 4-9
Called from Backtrace.task1 in file "backtrace.ml", line 29, characters 4-10
Re-raised at Stdlib__Effect.discontinue_with_backtrace.(fun) in file "effect.ml", line 74, characters 39-73
Called from Stdlib__Effect.perform in file "effect.ml", line 45, characters 12-31
Called from Backtrace.task2 in file "backtrace.ml", line 36, characters 4-28
